### ISSUE TITLE
Use pipes instead of veth interfaces for tests

### ISSUE THREAD

**Issue by 4tXJ7f** [p4pktgen/p4pktgen#2]
This will allow for easy recording of bmv2 outputs, won't require root anymore, and might be more efficient.

**Comment by jafingerhut** [comment]
A related idea -- what about making the default behavior of p4pktgen _not_ to run simple_switch and check its results against its behavior, but to simply generate its output, including the new test-cases.json file that is currently only in a PR.  When something like that is merged in, it contains all info needed to run simple_switch tests, or can be with some small extensions.

So you can either run p4pktgen in a mode where it generates the test cases, but does not run them (perhaps the new default behavior), or where it generates them and compares the expected vs. actual results with simple_switch.

The only noticeable change in behavior I could imagine with such an arrangement is that right now if there is a miscompare with simple_switch, the depth-first search backs off from that failed path immediately.  If we changed it as described here, p4pktgen would keep going deeper, because it wouldn't know about the miscompare.

**Comment by jafingerhut** [comment]
We have recently committed changes that no longer use veth interfaces to send packets to/from simple_switch, instead using Unix named pipe files in pcap format to do so, like bmv2stf.py does in the p4lang/p4c repository (and our implementation was heavily informed by theirs, since they had worked out a lot of the details of how to make that work already).

There is also a command line option not to run simple_switch while generating test cases.

There is not yet a command line option to read previously-generated test cases from a test-cases.json file and run them through simple_switch, but that should be fairly straightforward to implement.  I'll close this issue and create a separate one suggesting that enhancement.
